#:kivy 2.3.1

<EscritaScreen>:
    name: "escrita"

    BoxLayout:
        orientation: "vertical"
        padding: 20

        canvas.before:
            Color:
                rgb: 0.94, 0.94, 0.94

            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Escrita Modbus"
            font_size: 28
            bold: True
            color: 0, 0, 0, 1

        Label:
            text: "Funcionalidade em desenvolvimento."
            color: 0, 0, 0, 1